"""Initial migration

Revision ID: 262064abaad1
Revises:
Create Date: 2026-08-03 20:17:24.768165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "262064abaad1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cached_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("user_data", sa.JSON(), nullable=True),
        sa.Column("repositories_data", sa.JSON(), nullable=True),
        sa.Column("events_data", sa.JSON(), nullable=True),
        sa.Column("languages_data", sa.JSON(), nullable=True),
        sa.Column("complexity_score", sa.Float(), nullable=True),
        sa.Column("consistency_score", sa.Float(), nullable=True),
        sa.Column("collaboration_score", sa.Float(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("report_data", sa.JSON(), nullable=True),
        sa.Column("share_token", sa.String(length=64), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column(
            "cached_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cache_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cached_profiles_share_token"),
        "cached_profiles",
        ["share_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_cached_profiles_username"),
        "cached_profiles",
        ["username"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cached_profiles_username"), table_name="cached_profiles"
    )
    op.drop_index(
        op.f("ix_cached_profiles_share_token"), table_name="cached_profiles"
    )
    op.drop_table("cached_profiles")
    # ### end Alembic commands ###
